# Generated by Django 2.1.2 on 2018-11-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pruebas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expresion', models.CharField(max_length=100)),
                ('respuesta', models.CharField(max_length=1500)),
            ],
        ),
    ]
